name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  Continuous-Deployment:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: self-hosted

    steps:
      - name: Set up JDK 21 (Amazon Corretto)
        uses: actions/setup-java@v4
        with:
          distribution: corretto
          java-version: 21

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: application-jar
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}

      - name: Deploy application
        run: |
          set -euo pipefail
          set -x  # 실행되는 명령어 추적

          JAR_FILE=$(find . -name "*.jar" | head -n 1)

          if [ -z "$JAR_FILE" ]; then
            echo "ERROR: JAR file not found."
            exit 1
          fi

          echo "Deploying JAR file: $JAR_FILE"

          # Find and stop the running application (if any)
          PID=$(pgrep -f "$JAR_FILE" || true)
          if [ -n "$PID" ]; then
            echo "Stopping running application with PID: $PID"
            kill -15 "$PID" || true
            # Wait up to 10 seconds for process termination
            for i in {1..10}; do
              if ! ps -p "$PID" > /dev/null; then
                echo "Application stopped successfully."
                break
              fi
              sleep 1
            done
          else
            echo "No running application found."
          fi

          # Start the new application
          echo "Starting application..."
          nohup java -jar "$JAR_FILE" > app.log 2>&1 &

          # Verify that the application has started
          sleep 15
          NEW_PID=$(pgrep -f "$JAR_FILE" || true)
          if [ -n "$NEW_PID" ]; then
            echo "Application started successfully with PID: $NEW_PID"
            echo "Check logs with: tail -f app.log"
          else
            echo "ERROR: Application failed to start. Check app.log for details."
            cat app.log
            exit 1
          fi
